default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: tests
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.2.1
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
